import test from 'node:test';import assert from 'node:assert/strict';import express from 'express';
import {createPersonalPlanAI,checkedProposals,aiContext,mealCandidates} from '../src/services/ai/personalPlan.js';
import {createPersonalPlanRouter} from '../src/routes/personal-plan.js';
import {foods,recipes} from '../private/mi-plan/src/data.js';
import {effectiveIngredients,shoppingList,checkAIProposal} from '../private/mi-plan/src/engine.js';
import {decode} from '../private/mi-plan/src/storage.js';
const reply=obj=>async()=>({content:[{type:'text',text:JSON.stringify(obj)}]});
test('Claude sets the quantity and the app checks it against SMAE group values',async()=>{let sent;const ask=createPersonalPlanAI({generate:async req=>{sent=req;return reply({options:[{id:'orange',quantity:4}]})();}});const r=await ask({recipeId:'b0',index:0,question:'Quiero naranja'});assert.equal(r.usedAI,true);assert.equal(r.suggestions[0].quantity,4);assert.equal(r.suggestions[0].after.kcal,r.suggestions[0].before.kcal);assert.doesNotMatch(JSON.stringify(sent),/saidromero|Alondra|Osorno/);assert.match(sent.messages[0].content,/aportePorEquivalente/);});
test('cross-group proposals are allowed but their nutrients are computed by the app',async()=>{const ask=createPersonalPlanAI({generate:reply({options:[{id:'panela',quantity:14}]})});const r=await ask({recipeId:'d3',index:3,question:'Queso panela'});assert.equal(r.suggestions.length,1);const s=r.suggestions[0];assert.equal(s.sameGroup,false);assert.equal(s.before.kcal,19);assert.equal(s.after.kcal,19);assert.ok(Math.abs(s.after.proteina-2.45)<0.1);});
test('quantities far from the original energy are discarded, not shown',async()=>{const ask=createPersonalPlanAI({generate:reply({options:[{id:'orange',quantity:20},{id:'panela',quantity:400}]})});const r=await ask({recipeId:'b0',index:0,question:'Naranja'});assert.deepEqual(r.suggestions,[]);assert.match(r.message,/alejaban demasiado/);});
test('invalid, invented or unverified model responses never become swaps',()=>{const ctx=aiContext('b0',0);assert.throws(()=>checkedProposals('not json',ctx));assert.throws(()=>checkedProposals('{"ids":["orange"]}',ctx));for(const bad of [{id:'invented',quantity:1},{id:'extra5',quantity:1},{id:'orange',quantity:'4'},{id:'orange',quantity:-4},{id:'orange'}])assert.equal(checkedProposals(JSON.stringify({options:[bad]}),ctx).suggestions.length,0,JSON.stringify(bad));});
test('ingredient without quantity or documented nutrients never calls Claude',async()=>{let called=false;const ask=createPersonalPlanAI({generate:async()=>{called=true;}});for(const [id,i] of [['c0',6],['c1',8],['a1',6],['s2',0]]){const r=await ask({recipeId:id,index:i,question:'Algo'});assert.equal(r.usedAI,false,id+i);}assert.equal(called,false);});
test('held c1 shredded beef can be asked to Claude and shows the fat difference',async()=>{const ask=createPersonalPlanAI({generate:reply({options:[{id:'chicken',quantity:90}]})});const r=await ask({recipeId:'c1',index:2,question:'Pollo'});assert.equal(r.usedAI,true);const s=r.suggestions[0];assert.equal(s.before.grasa,15);assert.equal(s.after.grasa,3);assert.equal(mealCandidates('c1',2).candidates.length,0);});
test('a confirmed Claude swap keeps its quantity in the menu and the shopping list, and survives storage',()=>{const c0=recipes.find(r=>r.id==='c0');const changes={2:{target:'salmon',quantity:80,by:'claude'}};const items=effectiveIngredients(c0,changes,foods);assert.equal(items[2].foodId,'salmon');assert.equal(items[2].quantity,80);assert.equal(items[2].byAI,true);assert.equal(shoppingList([{recipe:c0,changes}],foods).find(r=>r.foodId==='salmon').quantity,80);const back=decode(JSON.stringify({version:1,changes:{'2026-09-14':{c0:changes}}}));assert.deepEqual(back.changes['2026-09-14'].c0[2],{target:'salmon',quantity:80,by:'claude'});const tampered=effectiveIngredients(c0,{2:{target:'salmon',quantity:900}},foods);assert.equal(tampered[2].foodId,'beef');assert.equal(decode(JSON.stringify({version:1,changes:{'2026-09-14':{c0:{2:{target:'salmon',quantity:'x'}}}}})).changes['2026-09-14'].c0[2],undefined);});
test('the kcal guard is the same rule on server and browser',()=>{const beef={foodId:'beef',quantity:90,unit:'gramos'};assert.equal(checkAIProposal(beef,'salmon',90,foods).ok,true);assert.equal(checkAIProposal(beef,'salmon',300,foods).ok,false);assert.equal(checkAIProposal({foodId:'onion',quantity:.25,unit:'pieza'},'tomato',1,foods).ok,false);});
test('within a family the equivalents rule wins over calories',()=>{const d0=recipes.find(r=>r.id==='d0'),pollo=d0.ingredients.find(i=>i.foodId==='chicken');assert.equal(checkAIProposal(pollo,'egg',3,foods).ok,true,'pechuga 90 g → 3 huevos: misma proteína');const c1=recipes.find(r=>r.id==='c1');assert.equal(checkAIProposal(c1.ingredients[2],'chicken',168.75,foods).ok,false,'169 g de pollo duplica la proteína');assert.equal(checkAIProposal(c1.ingredients[2],'chicken',90,foods).ok,true);const a0=recipes.find(r=>r.id==='a0');assert.equal(checkAIProposal(a0.ingredients[0],'croissant',1,foods).ok,true,'2 panes → 1 croissant: mismos hidratos');});
test('unknown selections rejected',()=>{assert.throws(()=>aiContext('nope',0));assert.throws(()=>aiContext('b0',-1));assert.throws(()=>mealCandidates('nope',0));});
test('empty selection returns non-actionable guidance',async()=>{const ask=createPersonalPlanAI({generate:reply({options:[]})});const r=await ask({recipeId:'b0',index:0,question:'Pizza'});assert.deepEqual(r.suggestions,[]);assert.match(r.message,/no está en el catálogo/);});
test('endpoint needs owner, origin and explicit consent before provider',async()=>{
 const app=express();app.use(express.json());let calls=0;
 app.use('/mi-plan',createPersonalPlanRouter({resolveSession:req=>req.headers['x-test-owner']?{uid:'adm_1763511804130',email:'saidromero19@gmail.com',role:'admin'}:null,findAdmin:async()=>({id:'adm_1763511804130',email:'saidromero19@gmail.com',role:'admin'}),askAI:async()=>{calls++;return {suggestions:[]};}}));
 const server=app.listen(0,'127.0.0.1');await new Promise(r=>server.on('listening',r));
 const url='http://127.0.0.1:'+server.address().port+'/mi-plan/suggest';
 const post=(headers={},body={recipeId:'b0',index:0,question:'Naranja',consent:true})=>fetch(url,{method:'POST',headers:{'Content-Type':'application/json',...headers},body:JSON.stringify(body)});
 try{assert.equal((await post()).status,401);assert.equal((await post({'x-test-owner':'1',Origin:'https://evil.example'})).status,403);assert.equal((await post({'x-test-owner':'1',Origin:'https://venuscosmetologia.com.mx'},{recipeId:'b0',index:0,question:'Naranja',consent:false})).status,400);assert.equal(calls,0);assert.equal((await post({'x-test-owner':'1',Origin:'https://venuscosmetologia.com.mx'})).status,200);assert.equal(calls,1);}finally{await new Promise(r=>server.close(r));}
});
