import test from 'node:test';import assert from 'node:assert/strict';import express from 'express';import cookieParser from 'cookie-parser';import jwt from 'jsonwebtoken';
import {createPersonalPlanRouter} from '../src/routes/personal-plan.js';
import {foods,recipes,menuForDate} from '../private/mi-plan/src/data.js';
import {proposeSwap,effectiveIngredients,shoppingList} from '../private/mi-plan/src/engine.js';
const owner={id:'adm_1763511804130',email:'saidromero19@gmail.com',role:'admin'},secret='test-only-personal-plan-secret';
async function fixture(fn,findAdmin=async()=>owner){const app=express();app.use(cookieParser());app.use('/mi-plan',createPersonalPlanRouter({resolveSession:req=>req.cookies.adm?jwt.verify(req.cookies.adm,secret,{algorithms:['HS256']}):null,findAdmin}));const server=app.listen(0,'127.0.0.1');await new Promise(resolve=>server.on('listening',resolve));const url='http://127.0.0.1:'+server.address().port;const cookie=(claims={uid:owner.id,email:owner.email,role:owner.role})=>'adm='+jwt.sign(claims,secret);try{await fn(url,cookie);}finally{await new Promise(resolve=>server.close(resolve));}}
test('anonymous document goes to dedicated login without revealing plan',()=>fixture(async url=>{const r=await fetch(url+'/mi-plan/',{redirect:'manual'});assert.equal(r.status,302);assert.equal(r.headers.get('location'),'/mi-plan/entrar');assert.match(r.headers.get('cache-control'),/no-store/);}));
test('anonymous data and source requests fail closed',()=>fixture(async url=>{for(const p of ['/src/data.js','/src/app.js','/src/storage.js','/src/engine.js','/session']){const r=await fetch(url+'/mi-plan'+p);assert.equal(r.status,401);assert.doesNotMatch(await r.text(),/Licuado|Manzana/);}}));
test('only generic login resources are anonymous',()=>fixture(async url=>{for(const p of ['/entrar','/login.js','/login.css']){const r=await fetch(url+'/mi-plan'+p);assert.equal(r.status,200);assert.match(r.headers.get('cache-control'),/no-store/);assert.doesNotMatch(await r.text(),/adm_1763511804130|saidromero19|Licuado/);}}));
test('other admin, reception and identity mismatches denied',()=>fixture(async(url,cookie)=>{for(const claims of [{uid:'other',email:owner.email,role:'admin'},{uid:owner.id,email:'other@example.com',role:'admin'},{uid:owner.id,email:owner.email,role:'recepcion'}]){const r=await fetch(url+'/mi-plan/src/data.js',{headers:{Cookie:cookie(claims)}});assert.equal(r.status,403);}}));
test('owner receives protected assets with privacy headers',()=>fixture(async(url,cookie)=>{for(const p of ['/','/src/data.js','/src/app.js','/src/style.css','/session']){const r=await fetch(url+'/mi-plan'+p,{headers:{Cookie:cookie()}});assert.equal(r.status,200);assert.match(r.headers.get('cache-control'),/private, no-store/);assert.match(r.headers.get('content-security-policy'),/frame-ancestors 'none'/);assert.equal(r.headers.get('access-control-allow-origin'),null);}}));
test('invalid token rejected',()=>fixture(async url=>{const r=await fetch(url+'/mi-plan/src/data.js',{headers:{Cookie:'adm=invalid'}});assert.equal(r.status,401);}));
test('removed or demoted owner denied despite valid token',()=>fixture(async(url,cookie)=>{const r=await fetch(url+'/mi-plan/src/data.js',{headers:{Cookie:cookie()}});assert.equal(r.status,403);},async()=>({...owner,role:'recepcion'})));
test('database failure does not expose assets',()=>fixture(async(url,cookie)=>{const r=await fetch(url+'/mi-plan/src/data.js',{headers:{Cookie:cookie()}});assert.equal(r.status,503);},async()=>{throw Error('offline');}));
test('private namespace does not expose arbitrary files',()=>fixture(async(url,cookie)=>{for(const p of ['/README.md','/src/../../server.js','/package.json','/login.html','/src/data.js.map']){const r=await fetch(url+'/mi-plan'+p,{headers:{Cookie:cookie()}});assert.equal(r.status,404);}}));
test('published copy retains safe exchanges and date-keyed inputs',()=>{const r=recipes.find(r=>r.id==='b0');assert.equal(proposeSwap(r.ingredients[0],'orange',foods).quantity,4);assert.equal(proposeSwap({foodId:'beef',quantity:90,unit:'gramos'},'chicken',foods).status,'pending');assert.equal(proposeSwap({foodId:'requeson',quantity:9,unit:'cucharada'},'chicken',foods).status,'pending');assert.equal(effectiveIngredients(r,{0:'orange'},foods)[0].quantity,4);assert.equal(shoppingList([{recipe:r,changes:{0:'orange'}}],foods).find(x=>x.foodId==='orange').quantity,4);assert.equal(menuForDate('2026-09-14').length,5);});
