import {readFileSync,existsSync} from 'node:fs';
import assert from 'node:assert/strict';
const root=new URL('../',import.meta.url);
assert(existsSync(new URL('src/mx/venus/mojileds/MainActivity.java',root)),'Native activity must exist');
const main=readFileSync(new URL('src/mx/venus/mojileds/MainActivity.java',root),'utf8');
const gpio=readFileSync(new URL('src/mx/venus/mojileds/GpioWhitePort.java',root),'utf8');
for(const text of ['request.isForMainFrame()', 'request.hasGesture()', 'onPause()', 'onDestroy()', 'onReceivedSslError', 'onReceivedError','onPermissionRequestCanceled','setAllowFileAccess(false)','setAllowContentAccess(false)','MIXED_CONTENT_NEVER_ALLOW','RESOURCE_VIDEO_CAPTURE','newSingleThreadScheduledExecutor','VenusMoji/0.8.0']) assert(main.includes(text),text);
assert(!main.includes('addJavascriptInterface'));
assert(!main.includes('RESOURCE_AUDIO_CAPTURE'));
assert(gpio.includes('OsConstants.O_WRONLY | OsConstants.O_CLOEXEC'));
assert(!/Os\.read|FileInputStream|RandomAccessFile|O_RDWR|O_CREAT/.test(gpio));
assert.equal((gpio.match(/\/sys\/class\/fise_gpio\d/g)||[]).join(''),'/sys/class/fise_gpio0');
const manifest=readFileSync(new URL('AndroidManifest.xml',root),'utf8');
assert.equal((manifest.match(/uses-permission/g)||[]).length,2);
assert(manifest.includes('versionCode="8"')); assert(manifest.includes('minSdkVersion="26"'));
console.log('PASS native structural safety guards (not runtime/device tests)');
